export const VIETNAM_PROVINCES = [
  "An Giang", "Bắc Ninh", "Cà Mau", "Cao Bằng", "Cần Thơ", "Đà Nẵng",
  "Đắk Lắk", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Nội",
  "Hà Tĩnh", "Hải Phòng", "Hưng Yên", "Huế", "Khánh Hòa", "Lai Châu",
  "Lâm Đồng", "Lạng Sơn", "Lào Cai", "Nghệ An", "Ninh Bình", "Phú Thọ",
  "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sơn La", "Tây Ninh", "Thanh Hóa",
  "Thái Nguyên", "TP Hồ Chí Minh", "Tuyên Quang", "Vĩnh Long",
] as const;

const provinceByLegacyIsoRegion: Record<string, (typeof VIETNAM_PROVINCES)[number]> = {
  "01": "Lai Châu",
  "02": "Lào Cai",
  "03": "Tuyên Quang",
  "04": "Cao Bằng",
  "05": "Sơn La",
  "06": "Lào Cai",
  "07": "Tuyên Quang",
  "09": "Lạng Sơn",
  "13": "Quảng Ninh",
  "14": "Phú Thọ",
  "18": "Ninh Bình",
  "20": "Hưng Yên",
  "21": "Thanh Hóa",
  "22": "Nghệ An",
  "23": "Hà Tĩnh",
  "24": "Quảng Trị",
  "25": "Quảng Trị",
  "26": "Huế",
  "27": "Đà Nẵng",
  "28": "Quảng Ngãi",
  "29": "Quảng Ngãi",
  "30": "Gia Lai",
  "31": "Gia Lai",
  "32": "Đắk Lắk",
  "33": "Đắk Lắk",
  "34": "Khánh Hòa",
  "35": "Lâm Đồng",
  "36": "Khánh Hòa",
  "37": "Tây Ninh",
  "39": "Đồng Nai",
  "40": "Lâm Đồng",
  "41": "Tây Ninh",
  "43": "TP Hồ Chí Minh",
  "44": "An Giang",
  "45": "Đồng Tháp",
  "46": "Đồng Tháp",
  "47": "An Giang",
  "49": "Vĩnh Long",
  "50": "Vĩnh Long",
  "51": "Vĩnh Long",
  "52": "Cần Thơ",
  "53": "Thái Nguyên",
  "54": "Bắc Ninh",
  "55": "Cà Mau",
  "56": "Bắc Ninh",
  "57": "TP Hồ Chí Minh",
  "58": "Đồng Nai",
  "59": "Cà Mau",
  "61": "Hải Phòng",
  "63": "Ninh Bình",
  "66": "Hưng Yên",
  "67": "Ninh Bình",
  "68": "Phú Thọ",
  "69": "Thái Nguyên",
  "70": "Phú Thọ",
  "71": "Điện Biên",
  "72": "Lâm Đồng",
  "73": "Cần Thơ",
  CT: "Cần Thơ",
  DN: "Đà Nẵng",
  HN: "Hà Nội",
  HP: "Hải Phòng",
  SG: "TP Hồ Chí Minh",
};

export function normalizeVercelRegion(countryHeader: string | null, regionHeader: string | null) {
  const countryCode = countryHeader?.trim().toUpperCase().slice(0, 2) || null;
  const regionCode = regionHeader?.trim().toUpperCase().replace(/^VN-/, "").slice(0, 16) || null;
  const provinceName = countryCode === "VN" && regionCode
    ? provinceByLegacyIsoRegion[regionCode] ?? null
    : null;
  return { countryCode, regionCode, provinceName };
}
