import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Bot, BrainCircuit, Sparkles, Workflow } from "lucide-react";
import { HeroSearch } from "@/components/hero-search";
import { JsonLd } from "@/components/json-ld";
import { PremiumHeroCard } from "@/components/premium-hero-card";
import { TutorialCard } from "@/components/tutorial-card";
import { getTutorialSummaries as getTutorials } from "@/lib/tutorial-data";
import { getTutorialViewCounts } from "@/lib/view-counts";
import { absoluteUrl, siteConfig } from "@/lib/site";
export const metadata:Metadata={alternates:{canonical:absoluteUrl("/")},openGraph:{url:absoluteUrl("/"),title:"AINextGen — Kiến thức AI thế hệ mới",description:siteConfig.description}};
export const revalidate=300;
const topics=[[BrainCircuit,"AI nền tảng","Hiểu LLM, RAG và cách AI hoạt động","AI Fundamentals"],[Bot,"Prompting","Viết prompt rõ, chính xác và tái sử dụng","Prompting"],[Workflow,"Automation","Kết nối AI vào quy trình công việc","Automation"],[Sparkles,"Creative AI","Tạo nội dung, hình ảnh và video","Creative AI"]] as const;
const roadmap=[["01","Hiểu","Nắm cách AI hoạt động, điểm mạnh và giới hạn."],["02","Thực hành","Dùng prompt và công cụ AI cho việc thật mỗi ngày."],["03","Tự động hóa","Ghép công cụ thành workflow có kiểm soát."]];
export default async function Home(){const [summaries,viewCounts]=await Promise.all([getTutorials(),getTutorialViewCounts()]);const tutorials=summaries.map(t=>({...t,view_count:viewCounts[t.slug]??0}));return <>
 <JsonLd data={{"@context":"https://schema.org","@type":"Organization",name:siteConfig.name,url:siteConfig.url,logo:absoluteUrl("/icon")}}/>
 <JsonLd data={{"@context":"https://schema.org","@type":"WebSite",name:siteConfig.name,url:siteConfig.url,description:siteConfig.description,inLanguage:"vi-VN",potentialAction:{"@type":"SearchAction",target:`${absoluteUrl("/search")}?q={search_term_string}`,"query-input":"required name=search_term_string"}}}/>
 <section className="overflow-hidden bg-gradient-to-br from-[#e8f8ee] via-[#f8faf8] to-[#f8f1dc]"><div className="hero-heartbeat" aria-hidden="true"><svg viewBox="0 0 1440 240" preserveAspectRatio="none" focusable="false"><defs><linearGradient id="heartbeat-gradient" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stopColor="#7657ff" stopOpacity="0"/><stop offset=".18" stopColor="#7657ff"/><stop offset=".52" stopColor="#53eee0"/><stop offset=".84" stopColor="#9a85ff"/><stop offset="1" stopColor="#9a85ff" stopOpacity="0"/></linearGradient></defs><path className="hero-heartbeat-base" pathLength="1" d="M0 126 H250 L280 126 L302 93 L326 170 L354 38 L385 145 L410 126 H680 L710 126 L730 105 L752 151 L778 67 L806 137 L830 126 H1100 L1128 126 L1148 98 L1171 160 L1197 54 L1226 141 L1250 126 H1440"/><path className="hero-heartbeat-flow" pathLength="1" d="M0 126 H250 L280 126 L302 93 L326 170 L354 38 L385 145 L410 126 H680 L710 126 L730 105 L752 151 L778 67 L806 137 L830 126 H1100 L1128 126 L1148 98 L1171 160 L1197 54 L1226 141 L1250 126 H1440"/></svg></div><div className="container-page grid items-center gap-10 py-16 md:grid-cols-2 md:py-24"><div><span className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1.5 text-sm font-bold text-brand-700 shadow"><Sparkles size={16}/> Học AI · Làm thật · Tiến xa</span><h1 className="mt-6 text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">Làm chủ AI trong <span className="text-brand-700">thời đại mới.</span></h1><p className="mt-5 max-w-xl text-lg leading-8 text-black/60">Tutorial dễ hiểu, prompt thực chiến và workflow có thể áp dụng ngay — dù bạn mới bắt đầu hay đang xây sản phẩm AI.</p><HeroSearch/></div><PremiumHeroCard/></div></section>
 <section className="container-page py-16"><div className="flex items-end justify-between"><div><p className="font-bold text-brand-700">Bắt đầu từ đây</p><h2 className="mt-2 text-3xl font-black">Học theo chủ đề</h2></div><Link href="/tutorials" className="hidden items-center gap-1 font-bold text-brand-700 sm:flex">Xem thư viện <ArrowRight size={18}/></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{topics.map(([Icon,title,text,category])=><Link key={title} href={`/tutorials?category=${encodeURIComponent(category)}`} className="card p-5 transition hover:-translate-y-1 hover:border-brand-500/50"><Icon className="text-cyan-300"/><h3 className="mt-4 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-black/50">{text}</p></Link>)}</div></section>
 <section className="container-page py-8"><p className="font-bold text-brand-700">Mới và nổi bật</p><h2 className="mt-2 text-3xl font-black">Tutorial thực chiến</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{tutorials.slice(0,6).map(t=><TutorialCard key={t.id} tutorial={t}/>)}</div></section>
 <section id="roadmap" className="container-page py-16"><div className="rounded-3xl border border-white/10 bg-[#0b1020] px-6 py-12 md:px-12"><p className="font-bold text-brand-700">Lộ trình 30 ngày</p><h2 className="mt-2 max-w-2xl text-3xl font-black">Không cần học mọi thứ. Học đúng thứ bạn cần.</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{roadmap.map(([n,t,d])=><div key={n} className="rounded-2xl border border-white/10 bg-white/5 p-5"><span className="text-sm font-black text-cyan-300">{n}</span><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-black/55">{d}</p></div>)}</div></div></section>
 </>}
