"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { slugify } from "@/lib/utils";
const base=z.object({name:z.string().trim().min(2),slug:z.string().trim().optional(),description:z.string().optional()});
async function requireAdmin(){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login");return db}
export async function saveTaxonomy(type:"categories"|"brands",formData:FormData){const input=base.parse({name:formData.get("name"),slug:formData.get("slug")||undefined,description:formData.get("description")||undefined});const db=await requireAdmin();const id=String(formData.get("id")||"");const values={...input,slug:input.slug||slugify(input.name),is_active:formData.get("is_active")==="on"};const {error}=id?await db.from(type).update(values).eq("id",id):await db.from(type).insert(values);if(error)throw new Error(error.message);revalidatePath(`/admin/${type}`);revalidatePath("/")}
export async function deleteRecord(type:"categories"|"brands"|"products"|"affiliate_links",id:string){const db=await requireAdmin();const {error}=await db.from(type).delete().eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin");revalidatePath("/products")}
const productSchema=z.object({name:z.string().trim().min(2),slug:z.string().optional(),short_description:z.string().optional(),description:z.string().optional(),thumbnail_url:z.string().url().or(z.literal("")),category_id:z.string().uuid().or(z.literal("")),brand_id:z.string().uuid().or(z.literal("")),rating:z.coerce.number().min(0).max(5)});
export async function saveProduct(formData:FormData){const input=productSchema.parse(Object.fromEntries(formData));const db=await requireAdmin();const id=String(formData.get("id")||"");const values={...input,slug:input.slug||slugify(input.name),category_id:input.category_id||null,brand_id:input.brand_id||null,thumbnail_url:input.thumbnail_url||null,is_featured:formData.get("is_featured")==="on",is_active:formData.get("is_active")==="on"};const {error}=id?await db.from("products").update(values).eq("id",id):await db.from("products").insert(values);if(error)throw new Error(error.message);revalidatePath("/admin/products");revalidatePath("/products")}
const offerSchema=z.object({product_id:z.string().uuid(),marketplace_name:z.string().trim().min(2),url:z.string().url(),price:z.coerce.number().nonnegative(),original_price:z.coerce.number().nonnegative().optional(),seller_name:z.string().optional(),warranty:z.string().optional(),shipping_info:z.string().optional(),voucher_info:z.string().optional(),product_condition:z.string().default("new"),note:z.string().optional()});
export async function saveOffer(formData:FormData){const input=offerSchema.parse(Object.fromEntries(formData));const db=await requireAdmin();const slug=slugify(input.marketplace_name);let {data:marketplace}=await db.from("marketplaces").select("id").eq("slug",slug).maybeSingle();if(!marketplace){const created=await db.from("marketplaces").insert({name:input.marketplace_name,slug}).select("id").single();if(created.error)throw new Error(created.error.message);marketplace=created.data}const values={product_id:input.product_id,marketplace_id:marketplace.id,url:input.url,price:input.price,original_price:input.original_price||null,seller_name:input.seller_name||null,warranty:input.warranty||null,shipping_info:input.shipping_info||null,voucher_info:input.voucher_info||null,product_condition:input.product_condition,note:input.note||null,is_official_store:formData.get("is_official_store")==="on",is_active:formData.get("is_active")==="on",last_checked_at:new Date().toISOString()};const {error}=await db.from("affiliate_links").insert(values);if(error)throw new Error(error.message);revalidatePath(`/admin/products/${input.product_id}/offers`);revalidatePath("/products")}
