import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, BadgeCheck, BookOpenCheck, Clock, ExternalLink, Flag, Sparkles, UserRound } from "lucide-react";
import { ArticleContent } from "@/components/article-content";
import { ArticleEngagementTracker } from "@/components/article-engagement-tracker";
import { JsonLd } from "@/components/json-ld";
import { TutorialCard } from "@/components/tutorial-card";
import { absoluteUrl, siteConfig } from "@/lib/site";
import type { Tutorial, TutorialSummary } from "@/types/tutorial";

const levels={beginner:"Beginner",intermediate:"Intermediate",advanced:"Advanced"};
const dateFormat=new Intl.DateTimeFormat("en-US",{dateStyle:"medium"});

export function EnglishTutorialArticle({tutorial,related=[]}:{tutorial:Tutorial;related?:TutorialSummary[]}){
  const path=`/en/tutorials/${tutorial.slug}`;const url=absoluteUrl(path);const articleImage=tutorial.cover_url||tutorial.content_blocks?.find(block=>block.type==="image")?.url;const image=articleImage||absoluteUrl("/opengraph-image");const updated=tutorial.updated_at||tutorial.published_at;const reviewed=tutorial.reviewed_at||updated;const author=tutorial.author_name||siteConfig.author;
  const reportHref=`mailto:${siteConfig.email}?subject=${encodeURIComponent(`Content issue: ${tutorial.title}`)}&body=${encodeURIComponent(`Hello AINextGen,\n\nI would like to report an issue in this article:\n${url}\n\nSection to review:\n\nIssue:\n\nReference source (optional):\n`)}`;
  const articleSchema={"@context":"https://schema.org","@type":"Article",headline:tutorial.title,description:tutorial.excerpt,datePublished:tutorial.published_at,dateModified:updated,inLanguage:"en",mainEntityOfPage:{"@type":"WebPage","@id":url},author:{"@type":"Person",name:author},publisher:{"@type":"Organization",name:siteConfig.name,url:siteConfig.url},articleSection:tutorial.category,keywords:[tutorial.category,...tutorial.tools].join(", "),image:[image]};
  const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:absoluteUrl("/en")},{"@type":"ListItem",position:2,name:"AI tutorials",item:absoluteUrl("/en/tutorials")},{"@type":"ListItem",position:3,name:tutorial.title,item:url}]};
  return <div className="container-page py-10"><ArticleEngagementTracker path={path} estimatedReadSeconds={tutorial.duration_minutes*60}/><JsonLd data={articleSchema}/><JsonLd data={breadcrumbSchema}/><nav aria-label="Breadcrumb"><Link href="/en/tutorials" className="inline-flex items-center gap-2 text-sm font-bold text-brand-700"><ArrowLeft size={17}/> Tutorial library</Link></nav>
    {articleImage&&<figure className="mx-auto mt-10 max-w-6xl"><div className="relative aspect-[16/9] overflow-hidden rounded-3xl border border-black/10 bg-white/5 shadow-2xl shadow-brand-500/10 sm:aspect-[16/7]"><Image src={articleImage} alt={`Cover image for ${tutorial.title}`} fill priority sizes="(max-width: 1280px) 100vw, 1152px" className="object-cover"/></div></figure>}
    <header className="mx-auto mt-10 max-w-4xl text-center"><span className="rounded-full border border-brand-500/30 bg-brand-500/10 px-3 py-1.5 text-sm font-bold text-brand-700">{tutorial.category}</span><h1 className="mt-6 text-4xl font-black leading-tight sm:text-5xl">{tutorial.title}</h1><div className="mt-6 flex flex-wrap justify-center gap-4 text-sm text-black/45"><span>{levels[tutorial.difficulty]}</span><span className="flex items-center gap-1"><Clock size={16}/>{tutorial.duration_minutes} min read</span><span className="flex items-center gap-1"><UserRound size={16}/>{author}</span><time dateTime={reviewed}>Edited {dateFormat.format(new Date(reviewed))}</time></div></header>
    <div className="mx-auto mt-12 grid max-w-6xl gap-8 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0 space-y-6"><article id="tutorial-content" className="card p-6 sm:p-8 lg:p-10"><ArticleContent blocks={tutorial.content_blocks} legacyContent={tutorial.content} intro={tutorial.excerpt}/></article><section className="card p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-brand-500/15 text-brand-700"><BadgeCheck size={24}/></span><div><h2 className="text-lg font-black">Edited by {author}</h2><p className="mt-2 text-sm leading-6 text-black/55">{tutorial.author_bio||"AINextGen edits tutorials for practical clarity, documents limitations, and updates them as AI tools change."}</p><p className="mt-2 text-xs font-semibold text-black/40">Editorial update: {dateFormat.format(new Date(reviewed))}</p></div></div></section><section className="rounded-2xl border border-amber-400/25 bg-amber-400/10 p-6 sm:p-8"><h2 className="text-lg font-black">Scope of this guide</h2><p className="mt-2 text-sm leading-6 text-black/55">Prompts and workflows are starting points for your own testing, not guarantees of views or income. Product features, pricing, and platform rules can change; compare the references below and verify AI output before use. AI may assist presentation, while an AINextGen editor remains responsible for the published version.</p></section>
      {Boolean(tutorial.source_references?.length)&&<section className="card p-6 sm:p-8"><h2 className="flex items-center gap-2 text-xl font-black"><BookOpenCheck className="text-cyan-300"/> References</h2><ol className="mt-5 space-y-3">{tutorial.source_references!.map((source,index)=><li key={`${source.url}-${index}`} className="flex gap-3 text-sm"><span className="font-black text-brand-700">{index+1}.</span><a href={source.url} target="_blank" rel="noopener noreferrer" className="min-w-0 break-words font-semibold hover:text-brand-700">{source.label}<ExternalLink className="ml-1 inline" size={13}/></a></li>)}</ol></section>}</div>
      <aside className="h-fit space-y-4 lg:sticky lg:top-24"><div className="card p-5"><p className="flex items-center gap-2 font-black"><Sparkles className="text-cyan-300" size={18}/> Tools used</p><div className="mt-4 flex flex-wrap gap-2">{tutorial.tools.map(tool=><span key={tool} className="rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-sm">{tool}</span>)}</div></div><div className="card p-5"><p className="font-black">Learn effectively</p><p className="mt-2 text-sm leading-6 text-black/55">Practice after each section and always verify AI-generated output.</p><a href={reportHref} className="btn-secondary mt-4 w-full gap-2 text-sm"><Flag size={16}/> Report an issue</a></div></aside></div>
    {related.length>0&&<section className="mx-auto mt-16 max-w-6xl"><h2 className="text-3xl font-black">Related tutorials</h2><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{related.map(item=><TutorialCard key={item.id} tutorial={item} locale="en"/>)}</div></section>}
  </div>;
}
