"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { BrandLogo } from "@/components/brand-logo";
import { localeFromPath, localizePath } from "@/lib/i18n";

export function SiteFooter(){
  const locale=localeFromPath(usePathname());const p=(path:string)=>localizePath(path,locale);const en=locale==="en";
  return <footer className="site-footer mt-20 border-t"><div className="container-page grid gap-10 py-12 sm:grid-cols-2 lg:grid-cols-4"><div><BrandLogo/><p className="mt-3 max-w-sm text-sm leading-6 text-black/60">{en?"AINextGen turns complex AI concepts into practical tutorials, prompts, and workflows you can use at work.":"AINextGen là nền tảng AI Next Gen Việt Nam với kiến thức dễ hiểu, thực tế và có thể áp dụng ngay vào công việc."}</p></div><div><p className="font-bold">{en?"Explore":"Khám phá"}</p><div className="mt-3 grid gap-2 text-sm text-black/60"><Link href={p("/tutorials")}>{en?"All tutorials":"Tất cả tutorial"}</Link><Link href={`${p("/tutorials")}?category=L%E1%BB%99+tr%C3%ACnh`}>{en?"AI learning roadmap":"Lộ trình học AI"}</Link><Link href={`${p("/tutorials")}?category=Prompting`}>{en?"Prompt library":"Thư viện prompt"}</Link><Link href={`${p("/tutorials")}?category=Automation`}>AI Automation</Link>{!en&&<a href="/rss.xml">Theo dõi RSS</a>}</div></div><div><p className="font-bold">AINextGen</p><div className="mt-3 grid gap-2 text-sm text-black/60"><Link href={p("/about")}>{en?"About":"Giới thiệu"}</Link><Link href={p("/contact")}>{en?"Contact":"Liên hệ"}</Link><Link href={p("/editorial-policy")}>{en?"Editorial policy":"Nguyên tắc biên tập"}</Link></div></div><div><p className="font-bold">{en?"Legal":"Pháp lý"}</p><div className="mt-3 grid gap-2 text-sm text-black/60"><Link href={p("/privacy")}>{en?"Privacy":"Quyền riêng tư"}</Link><Link href={p("/terms")}>{en?"Terms of use":"Điều khoản sử dụng"}</Link></div><p className="mt-4 text-xs leading-5 text-black/45">{en?"Always verify AI-generated output before using it for important decisions.":"Nội dung AI luôn cần được kiểm chứng trước khi áp dụng vào quyết định quan trọng."}</p></div></div><div className="border-t py-5 text-center text-xs text-black/45">© {new Date().getFullYear()} AINextGen · {en?"Practical AI knowledge.":"AI Next Gen Việt Nam."}</div></footer>;
}
