import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Bot, BrainCircuit, Sparkles, Workflow } from "lucide-react";
import { HeroSearch } from "@/components/hero-search";
import { JsonLd } from "@/components/json-ld";
import { TutorialCard } from "@/components/tutorial-card";
import { getEnglishTutorialSummaries } from "@/lib/tutorial-data";
import { getTutorialViewCounts } from "@/lib/view-counts";
import { absoluteUrl, siteConfig } from "@/lib/site";

export const revalidate=300;
export const metadata:Metadata={title:"Practical AI tutorials, prompts and workflows",description:"Learn AI through practical tutorials, reusable prompts, and step-by-step workflows from AINextGen.",alternates:{canonical:"/en",languages:{"vi-VN":"/",en:"/en","x-default":"/"}},openGraph:{locale:"en_US",url:"/en",title:"AINextGen | Practical AI tutorials",description:"Practical AI knowledge you can use at work."}};

const topics=[[BrainCircuit,"AI fundamentals","Understand LLMs, RAG, and how AI works","AI Fundamentals"],[Bot,"Prompting","Write clear, accurate, reusable prompts","Prompting"],[Workflow,"Automation","Connect AI to real work processes","Automation"],[Sparkles,"Creative AI","Create content, images, and video","Creative AI"]] as const;
const roadmap=[["01","Understand","Learn how AI works, what it does well, and where it fails."],["02","Practice","Use prompts and AI tools on real everyday tasks."],["03","Automate","Combine tools into reliable, human-reviewed workflows."]];

export default async function EnglishHome(){
  const [summaries,viewCounts]=await Promise.all([getEnglishTutorialSummaries(),getTutorialViewCounts()]);
  const tutorials=summaries.map(t=>({...t,view_count:viewCounts[t.slug]??0}));
  return <>
    <JsonLd data={{"@context":"https://schema.org","@type":"WebSite",name:siteConfig.name,url:absoluteUrl("/en"),description:"Practical AI tutorials, prompts, and workflows.",inLanguage:"en",potentialAction:{"@type":"SearchAction",target:`${absoluteUrl("/en/search")}?q={search_term_string}`,"query-input":"required name=search_term_string"}}}/>
    <section className="overflow-hidden bg-gradient-to-br from-[#e8f8ee] via-[#f8faf8] to-[#f8f1dc]"><div className="container-page grid items-center gap-10 py-16 md:grid-cols-2 md:py-24"><div><span className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1.5 text-sm font-bold text-brand-700 shadow"><Sparkles size={16}/> Learn AI · Build real things · Move forward</span><h1 className="mt-6 text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">Practical AI knowledge with <span className="text-brand-700">AINextGen.</span></h1><p className="mt-5 max-w-xl text-lg leading-8 text-black/60">Clear tutorials, field-tested prompts, and workflows you can apply right away—whether you are starting out or building an AI product.</p><HeroSearch locale="en"/></div><div className="card hidden min-h-80 overflow-hidden bg-[#0b1020] p-8 text-white md:flex md:flex-col"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">AINEXTGEN KNOWLEDGE PASS</p><h2 className="mt-auto max-w-md text-3xl font-black text-white">From AI beginner to confident power user.</h2><p className="mt-4 text-sm leading-6 text-white/55">Tutorials · Workflows · Reusable prompts</p></div></div></section>
    <section className="container-page py-16"><div className="flex items-end justify-between"><div><p className="font-bold text-brand-700">Start here</p><h2 className="mt-2 text-3xl font-black">Learn by topic</h2></div><Link href="/en/tutorials" className="hidden items-center gap-1 font-bold text-brand-700 sm:flex">Open the library <ArrowRight size={18}/></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{topics.map(([Icon,title,text,category])=><Link key={title} href={`/en/tutorials?category=${encodeURIComponent(category)}`} className="card p-5 transition hover:-translate-y-1 hover:border-brand-500/50"><Icon className="text-cyan-300"/><h3 className="mt-4 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-black/50">{text}</p></Link>)}</div></section>
    <section className="container-page py-8"><p className="font-bold text-brand-700">New and featured</p><h2 className="mt-2 text-3xl font-black">Practical tutorials</h2>{tutorials.length?<div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{tutorials.slice(0,6).map(t=><TutorialCard key={t.id} tutorial={t} locale="en"/>)}</div>:<div className="card mt-8 p-8"><h3 className="text-xl font-black">English tutorials are being prepared.</h3><p className="mt-2 text-black/55">The English interface is ready. Translate and publish articles from Admin to make them appear here.</p><Link href="/tutorials" hrefLang="vi" className="mt-4 inline-flex font-bold text-brand-700">Browse the Vietnamese library →</Link></div>}</section>
    <section id="roadmap" className="container-page py-16"><div className="rounded-3xl border border-white/10 bg-[#0b1020] px-6 py-12 text-white md:px-12"><p className="font-bold text-cyan-300">30-day roadmap</p><h2 className="mt-2 max-w-2xl text-3xl font-black text-white">You do not need to learn everything. Learn what moves your work forward.</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{roadmap.map(([n,t,d])=><div key={n} className="rounded-2xl border border-white/10 bg-white/5 p-5"><span className="text-sm font-black text-cyan-300">{n}</span><h3 className="mt-4 text-xl font-black text-white">{t}</h3><p className="mt-2 text-sm leading-6 text-white/55">{d}</p></div>)}</div></div></section>
  </>;
}
