-- Persist verified sources and local editorial covers for the twelve curated tutorials.
-- The fixed timestamp reflects the actual editorial review performed on 2026-08-15.

with verified(slug, cover_url, source_references) as (
  values
    ('nghien-cuu-voi-ai-khong-hallucination', 'https://ainextgen.io.vn/images/tutorials/nghien-cuu-voi-ai-khong-hallucination.webp', '[{"label":"NIST — Generative AI Profile","url":"https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"},{"label":"Google AI — Prompt design strategies","url":"https://ai.google.dev/gemini-api/docs/prompting-strategies"}]'::jsonb),
    ('prompt-engineering-tu-co-ban-den-thuc-chien', 'https://ainextgen.io.vn/images/tutorials/prompt-engineering-tu-co-ban-den-thuc-chien.webp', '[{"label":"OpenAI — Prompt engineering best practices","url":"https://help.openai.com/en/articles/10032626-prompt-engineering-best-practices-for-chatgpt"},{"label":"Google AI — Prompt design strategies","url":"https://ai.google.dev/gemini-api/docs/prompting-strategies"}]'::jsonb),
    ('tu-dong-tom-tat-cuoc-hop-voi-ai', 'https://ainextgen.io.vn/images/tutorials/tu-dong-tom-tat-cuoc-hop-voi-ai.webp', '[{"label":"Microsoft Learn — Craft effective prompts for Copilot","url":"https://learn.microsoft.com/en-us/training/paths/craft-effective-prompts-copilot-microsoft-365/"},{"label":"Make — OpenAI integration","url":"https://www.make.com/en/integrations/make/openai-gpt-3"}]'::jsonb),
    ('lo-trinh-hoc-ai-thuc-chien-30-ngay', 'https://ainextgen.io.vn/images/tutorials/lo-trinh-hoc-ai-thuc-chien-30-ngay.webp', '[{"label":"Google — Machine Learning Crash Course","url":"https://developers.google.com/machine-learning/crash-course"},{"label":"OpenAI Academy — Prompting","url":"https://academy.openai.com/public/clubs/work-users-ynjqu/resources/prompting"}]'::jsonb),
    ('llm-la-gi-cho-nguoi-moi', 'https://ainextgen.io.vn/images/tutorials/llm-la-gi-cho-nguoi-moi.webp', '[{"label":"Google — Introduction to large language models","url":"https://developers.google.com/machine-learning/crash-course/llm"},{"label":"Vaswani et al. — Attention Is All You Need","url":"https://arxiv.org/abs/1706.03762"}]'::jsonb),
    ('tao-hinh-anh-ai-dung-thuong-hieu', 'https://ainextgen.io.vn/images/tutorials/tao-hinh-anh-ai-dung-thuong-hieu.webp', '[{"label":"OpenAI — Image generation guide","url":"https://developers.openai.com/api/docs/guides/image-generation"},{"label":"Canva — Brand Hub","url":"https://www.canva.com/newsroom/news/home-for-every-brand/"}]'::jsonb),
    ('12-prompt-ai-cho-dan-van-phong', 'https://ainextgen.io.vn/images/tutorials/12-prompt-ai-cho-dan-van-phong.webp', '[{"label":"Microsoft Learn — Write effective prompts","url":"https://learn.microsoft.com/en-us/training/modules/write-effective-prompts-do-more-prompting/"},{"label":"OpenAI — Prompt engineering best practices","url":"https://help.openai.com/en/articles/10032626-prompt-engineering-best-practices-for-chatgpt"}]'::jsonb),
    ('content-calendar-tu-dong-voi-make-va-ai', 'https://ainextgen.io.vn/images/tutorials/content-calendar-tu-dong-voi-make-va-ai.webp', '[{"label":"Make — OpenAI integration","url":"https://www.make.com/en/integrations/make/openai-gpt-3"},{"label":"Notion — API quickstart","url":"https://developers.notion.com/guides/get-started/quick-start"}]'::jsonb),
    ('lo-trinh-prompt-engineer-8-tuan', 'https://ainextgen.io.vn/images/tutorials/lo-trinh-prompt-engineer-8-tuan.webp', '[{"label":"OpenAI — Prompt engineering best practices","url":"https://help.openai.com/en/articles/10032626-prompt-engineering-best-practices-for-chatgpt"},{"label":"OpenAI — Evals guide","url":"https://developers.openai.com/api/docs/guides/evals"},{"label":"Anthropic — Prompting best practices","url":"https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices"}]'::jsonb),
    ('rag-la-gi-va-cach-hoat-dong', 'https://ainextgen.io.vn/images/tutorials/rag-la-gi-va-cach-hoat-dong.webp', '[{"label":"Lewis et al. — Retrieval-Augmented Generation","url":"https://arxiv.org/abs/2005.11401"},{"label":"Google — Embeddings","url":"https://developers.google.com/machine-learning/crash-course/embeddings"}]'::jsonb),
    ('prompt-chaining-chia-viec-lon-thanh-nhiem-vu-nho', 'https://ainextgen.io.vn/images/tutorials/prompt-chaining-chia-viec-lon-thanh-nhiem-vu-nho.webp', '[{"label":"Google AI — Prompt design strategies","url":"https://ai.google.dev/gemini-api/docs/prompting-strategies"},{"label":"Anthropic — Prompting best practices","url":"https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices"}]'::jsonb),
    ('ai-agent-an-toan-voi-human-in-the-loop', 'https://ainextgen.io.vn/images/tutorials/ai-agent-an-toan-voi-human-in-the-loop.webp', '[{"label":"OpenAI Agents SDK — Human-in-the-loop","url":"https://openai.github.io/openai-agents-js/guides/human-in-the-loop/"},{"label":"NIST — AI Risk Management Framework","url":"https://www.nist.gov/itl/ai-risk-management-framework"}]'::jsonb)
)
update public.articles as article
set cover_url = verified.cover_url,
    source_references = verified.source_references,
    reviewed_at = timestamptz '2026-08-15 05:00:00+00',
    updated_at = timestamptz '2026-08-15 05:00:00+00'
from verified
where article.slug = verified.slug;